version: "3.7"

services:
  rchain:
    image: rchain/rnode:release-rnode-v0.7
    networks:
      - rchain-scan
    volumes:
      - ./scripts:/scripts:ro
      - ./rnode:/rnode:ro
    ports:
      - "40401:40401"
      - "40404:40404"
    command: -c /rnode/rnode.toml run


  tests:
    image: clojure:lein
    volumes:
      - ./:$PWD
    working_dir: $PWD
    depends_on:
      - rchain
    networks:
      - rchain-scan
    entrypoint: ./scripts/wait-for-rnode.sh
    environment:
      - RNODE__HOST=rchain
    tty: true
    command: lein test-refresh


  repl:
    image: clojure:lein
    volumes:
      - ./:$PWD
    working_dir: $PWD
    depends_on:
      - rchain
    networks:
      - rchain-scan
    entrypoint: ./scripts/wait-for-rnode.sh
    environment:
      - RNODE__HOST=rchain
    ports:
      - "3000:3000"
      - "7000:7000"
      - "7002:7002"
      - "3449:3449"
    command: lein repl :headless :host 0.0.0.0 :port 7000


  app:
    build: .
    networks:
      - rchain-scan
    depends_on:
      - rchain
    environment:
      - RNODE__HOST:rchain
    ports:
      - "3000:3000"

networks:
  rchain-scan:
