version: "2.1"

services:
  rchain:
    image: rchain/rnode:release-rnode-v0.7
    command: -c /rnode/rnode.toml run
    volumes:
      - ./scripts:/scripts:ro
      - ./rnode:/rnode:ro
    ports:
      - "40401:40401"
      - "40404:40404"
